### ISSUE TITLE
Colour Palette

### ISSUE THREAD

**Issue by rdtscp** [FlatMatch/ui#3]
What should be the colour palette for the website.
I have [generated](https://coolors.co/78a1bb-30332e-fffbfc-48beff-0b132b) a colour scheme that seems to fit with the new MyEd colour scheme.
Any feedback?

**Comment by dylanOshima** [comment]
I think it looks fine. What if we had a brighter color like: E8911A or FF9F1C instead of 30332E or 0B132B.
